export const arabicMainKeywords = [
  "نظام ERP",
  "برنامج ERP",
  "برنامج إدارة شركات",
  "نظام إدارة أعمال",
  "برنامج حسابات ومخازن",
  "برنامج مبيعات ومخازن",
  "برنامج ERP عربي",
  "ERP مصر",
  "ERP السعودية",
  "ERP الإمارات",
  "برنامج ERP للشركات الصغيرة",
  "برنامج ERP للشركات المتوسطة",
  "نظام ERP للمصانع",
  "برنامج إدارة مخازن",
  "برنامج حسابات للشركات",
  "برنامج CRM عربي",
  "برنامج HR ورواتب",
  "برنامج كاشير POS",
  "برنامج إدارة مشاريع",
  "برنامج إدارة عملاء",
  "نظام تقارير للشركات",
  "نظام أتمتة أعمال",
  "بديل Odoo عربي",
  "Odoo Alternative Arabic",
];

export const englishMainKeywords = [
  "ERP software",
  "ERP system",
  "Business management software",
  "Accounting ERP",
  "Inventory ERP",
  "CRM ERP",
  "POS ERP",
  "HR payroll software",
  "Manufacturing ERP",
  "ERP software Egypt",
  "ERP software Saudi Arabia",
  "ERP software UAE",
  "Arabic ERP software",
  "Odoo alternative",
  "ERP for small business",
  "ERP for medium business",
  "SaaS ERP platform",
  "Business operating system",
];

export const longTailKeywords = [
  "أفضل برنامج ERP لإدارة الشركات في مصر",
  "برنامج ERP عربي للشركات الصغيرة والمتوسطة",
  "برنامج حسابات ومخازن ومبيعات في نظام واحد",
  "برنامج إدارة مخزون وفواتير وموردين",
  "برنامج ERP للمصانع وإدارة الإنتاج",
  "نظام CRM وربط واتساب للشركات",
  "برنامج كاشير POS متصل بالمخزون والحسابات",
  "أفضل بديل Odoo للشركات العربية",
  "نظام إدارة شركات سحابي باللغة العربية",
  "برنامج ERP للشركات في السعودية والإمارات",
];

export function getCountryModifiers(): string[] {
  return [
    "مصر",
    "السعودية",
    "الإمارات",
    "الكويت",
    "قطر",
    "عمان",
    "البحرين",
    "العراق",
    "الأردن",
    "المغرب",
    "الجزائر",
    "تونس",
    "ليبيا",
    "السودان",
    "اليمن",
    "سوريا",
    "لبنان",
    "فلسطين",
  ];
}
