export const DEFAULT_ORG_SETTINGS = {
  company_name: "",
  company_tagline: "",
  company_address: "",
  company_phone: "",
  company_email: "",
  company_logo_data: "",
  bank_name: "",
  bank_account: "",
  vodafone_cash: "",
  default_tax_rate: 0,
  default_notes: "",
  print_client_logo_width_px: 120,
  print_client_logo_max_height_px: 40,
  hr_payroll_days_divisor: 30,
  hr_standard_work_hours_per_day: 8,
  hr_overtime_rate_multiplier: 1.25,
  hr_workday_start_time: "09:00",
  hr_workday_end_time: "17:00",
  hr_late_grace_minutes: 15,
  hr_early_leave_grace_minutes: 15,
  hr_weekend_days: [4, 5],
  hr_missing_attendance_counts_as_absence: true,
} as const;
